- name: Wait for client to come online
  become: no
  delegate_to: localhost
  wait_for:
    host: "{{ ansible_host }}"
    port: 22
- name: Write the host key to known hosts
  delegate_to: localhost
  shell: "ssh-keyscan -H {{ ansible_host }} >> ~/.ssh/known_hosts"
  become: no
- name: Set NTP settings
  ansible.builtin.lineinfile:
    path: /etc/chrony.conf
    line: "server {{ network_domain_controller }} iburst prefer"
- name: Join domain
  shell: | 
    echo "{{ domain_admin_password }}" | realm join {{ domain_long|lower }}
    history -c
- name: Configure AD logon usernames
  ansible.builtin.lineinfile:
    path: /etc/sssd/sssd.conf
    regexp: '^use_fully_qualified_names = '
    line: "use_fully_qualified_names = False"
- name: Configure AD user homedir
  ansible.builtin.lineinfile:
    path: /etc/sssd/sssd.conf
    regexp: '^fallback_homedir = '
    line: "fallback_homedir = /home/%u@%d"
- name: Restart SSSD
  systemd:
    name: sssd
    state: restarted