- name: Wait for client to come online
  become: no
  delegate_to: localhost
  wait_for:
    host: "{{ ansible_host }}"
    port: 5986
    timeout: 600
- name: Wait for domain controller to come online
  become: no
  delegate_to: localhost
  wait_for:
    host: "{{ network_domain_controller }}"
    port: 445
    timeout: 600
- name: Transfer update package
  win_copy:
    dest: C:\rsat.msu
    src: +FILES+/rsat.msu
  vars:
    ansible_command_timeout: 1200
    ansible_winrm_operation_timeout_sec: 1200
    ansible_winrm_read_timeout_sec: 1800
- name: Configure update package (Takes a long time...)
  win_command: cmd.exe /c "wusa.exe C:\rsat.msu /quiet /norestart" 
  vars:
    ansible_command_timeout: 1200
    ansible_winrm_operation_timeout_sec: 1200
    ansible_winrm_read_timeout_sec: 1800  
- name: Reboot system
  shell: 'sleep 2 && shutdown -r now'
  poll: 0
  async: 1
  