network:
    ethernets:
        eth0:
            dhcp4: no
            dhcp6: no
            addresses: [{{ new_ip }}/{{ network_prefix }}, ]
            gateway4:  {{ network_gateway }}
            nameservers:
                    addresses: [{{ network_dns_server }}]