- name: Wait for client to come online
  become: no
  delegate_to: localhost
  wait_for:
    host: "{{ ansible_host }}"
    port: 5986
    timeout: 600
- name: Wait for domain controller to come online
  become: no
  delegate_to: localhost
  wait_for:
    host: "{{ network_domain_controller }}"
    port: 445
    timeout: 600
- name: Add user to local administrator group
  win_command: cmd.exe /c "net localgroup Administrators {{ var_username }} /add" 

  